services:
  - type: web
    name: puppeteer-screenshot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 16
    buildpacks:
      - url: heroku/nodejs
      - url: https://github.com/jontewks/puppeteer-heroku-buildpack
